# Generated by Django 4.2.7 on 2023-12-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcasa_color_azul', models.IntegerField()),
                ('carcasa_color_verde', models.IntegerField()),
                ('carcasa_color_amarillo', models.IntegerField()),
                ('carcasa_color_morado', models.IntegerField()),
                ('carcasa_color_rosa', models.IntegerField()),
                ('carcasa_color_cyan', models.IntegerField()),
            ],
        ),
    ]
