# Generated by Django 4.2.7 on 2023-12-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='inventario',
        ),
        migrations.AddField(
            model_name='envio',
            name='solicitud',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.solicitud'),
        ),
    ]
