# Generated by Django 4.2.7 on 2023-12-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_inventariopc_inventariope_inventariopt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('cantidad_maxima', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('venta_maxima', models.IntegerField()),
                ('venta_minima', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='InventarioPC',
        ),
        migrations.DeleteModel(
            name='InventarioPE',
        ),
        migrations.DeleteModel(
            name='InventarioPT',
        ),
    ]
