# Generated by Django 4.2.7 on 2023-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_inventario_bom_inventario_status_inventario_stockl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Entregado'), (2, 'En Transito')]),
        ),
    ]
