# Generated by Django 4.2.7 on 2023-12-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicParts',
            fields=[
                ('parts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productos.parts')),
                ('cameras', models.IntegerField(default=0)),
                ('biometric_sensors', models.IntegerField(default=0)),
                ('baseband', models.IntegerField(default=0)),
                ('power_management', models.IntegerField(default=0)),
                ('processor', models.IntegerField(default=0)),
                ('nand', models.IntegerField(default=0)),
                ('dram', models.IntegerField(default=0)),
                ('accelerometer', models.IntegerField(default=0)),
                ('battery', models.IntegerField(default=0)),
                ('microphone', models.IntegerField(default=0)),
                ('speakers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlasticParts',
            fields=[
                ('parts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productos.parts')),
                ('carcasa_color_azul', models.IntegerField(default=0)),
                ('carcasa_color_verde', models.IntegerField(default=0)),
                ('carcasa_color_amarillo', models.IntegerField(default=0)),
                ('carcasa_color_morado', models.IntegerField(default=0)),
                ('carcasa_color_rosa', models.IntegerField(default=0)),
                ('carcasa_color_cyan', models.IntegerField(default=0)),
            ],
        ),
    ]
