# Generated by Django 4.2.7 on 2023-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_electronicparts_plasticparts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicparts',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='plasticparts',
            name='parts',
        ),
        migrations.AddField(
            model_name='electronicparts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasticparts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
    ]
