# Generated by Django 4.2.7 on 2023-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_envio_destino_alter_envio_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='destino',
            field=models.SmallIntegerField(choices=[('CDMX', 'Ciudad de Mexico'), ('QUERETARO', 'Queretaro'), ('MONTERREY', 'Monterrey')]),
        ),
        migrations.AlterField(
            model_name='envio',
            name='origen',
            field=models.SmallIntegerField(choices=[('TOLUCA', 'Toluca'), ('METEPEC', 'Metepec')]),
        ),
    ]
